sudo: required
language: generic

services:
  - docker
before_install:
  - docker build -t lebowski/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true lebowski/docker-react npm run test